// Package tor spawns local tor processes pinned to ExitNodes countries.
// Simplified port of lingling/lanes.py without stem: torrc + port wait.
package tor

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"lanvello/internal/lanes"
)

func BinaryName() string { return "tor" }

func FindTor() string {
	if v := os.Getenv("LANVELLO_TOR_EXE"); v != "" {
		return v
	}
	for _, c := range []string{"/usr/bin/tor", "/usr/local/bin/tor"} {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	if p, err := exec.LookPath("tor"); err == nil {
		return p
	}
	return ""
}

func writeTorrc(dir string, socksPort, ctrlPort int, country string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	exit := "{" + country + "}"
	if country == "*" {
		exit = "*"
	}
	cfg := "# generated by lanvello. do not edit.\n" +
		fmt.Sprintf("SocksPort 127.0.0.1:%d\n", socksPort) +
		fmt.Sprintf("ControlPort 127.0.0.1:%d\n", ctrlPort) +
		fmt.Sprintf("DataDirectory %s\n", dir) +
		"CookieAuthentication 1\n" +
		"MaxCircuitDirtiness 600\n" +
		"SocksTimeout 45\n" +
		"CircuitStreamTimeout 20\n" +
		"RunAsDaemon 0\n" +
		fmt.Sprintf("ExitNodes %s\nStrictNodes 1\n", exit)
	return os.WriteFile(filepath.Join(dir, "torrc"), []byte(cfg), 0o600)
}

func waitPort(addr string, timeout time.Duration) bool {
	dead := time.Now().Add(timeout)
	for time.Now().Before(dead) {
		c, err := net.DialTimeout("tcp", addr, 500*time.Millisecond)
		if err == nil {
			c.Close()
			return true
		}
		time.Sleep(500 * time.Millisecond)
	}
	return false
}

// Ensure starts one tor per lane when no explicit socks are given.
// It mutates lane SocksAddr/ExitIP best-effort; missing tor binary is not fatal.
func Ensure(m *lanes.Manager, dataDir string, base, ctrlBase int, timeout time.Duration) {
	bin := FindTor()
	if bin == "" {
		return
	}
	for _, l := range m.Lanes() {
		if l.SocksAddr != "" {
			continue
		}
		socks := base + l.Index - 1
		ctrl := ctrlBase + l.Index - 1
		dir := filepath.Join(dataDir, "lanes", fmt.Sprintf("tor-%d", l.Index))
		_ = writeTorrc(dir, socks, ctrl, l.Country)
		cmd := exec.Command(bin, "-f", filepath.Join(dir, "torrc"))
		cmd.Stdout = nil
		cmd.Stderr = nil
		if err := cmd.Start(); err != nil {
			continue
		}
		addr := fmt.Sprintf("127.0.0.1:%d", socks)
		if waitPort(addr, timeout) {
			l.SocksAddr = addr
			l.Healthy = true
		}
	}
}
